CREATE TABLE devices {
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  last_connection INTEGER NOT NULL,
  lon FLOAT NOT NULL,
  lat FLOAT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
}